name: "Build and deploy ASP.NET Core app to Azure Web App - online-bookstore-phoenix"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Restore
        run: dotnet restore backend/backend/backend.csproj

      - name: Build
        run: dotnet build backend/backend/backend.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish backend/backend/backend.csproj --configuration Release --no-build --output "${{ env.DOTNET_ROOT }}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5F377E5B669346BF97AEBD44684A080F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E5353009FF7C43A49C80AA68B6D0CF23 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E6AB3F99799D430B8064C99AF21A94E9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "online-bookstore-phoenix"
          slot-name: "Production"
          package: .
